/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spc.edu;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Bai25_TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form Bai25_TicTacToe
     */
    int turn = 2;
    int buttonused[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int pXwon[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int pOwon[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};

    int pXwon() {
        if (pXwon[0] == 1 && pXwon[1] == 1 && pXwon[2] == 1) {
            return 1;
        }
        if (pXwon[3] == 1 && pXwon[4] == 1 && pXwon[5] == 1) {
            return 1;
        }
        if (pXwon[6] == 1 && pXwon[7] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[0] == 1 && pXwon[3] == 1 && pXwon[6] == 1) {
            return 1;
        }
        if (pXwon[1] == 1 && pXwon[4] == 1 && pXwon[7] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[5] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[4] == 1 && pXwon[6] == 1) {
            return 1;
        }
        if (pXwon[0] == 1 && pXwon[4] == 1 && pXwon[8] == 1) {
            return 1;
        }
        return 0;
    }

    int pOwon() {
        if (pOwon[0] == 1 && pOwon[1] == 1 && pOwon[2] == 1) {
            return 1;
        }
        if (pOwon[3] == 1 && pOwon[4] == 1 && pOwon[5] == 1) {
            return 1;
        }
        if (pOwon[6] == 1 && pOwon[7] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[0] == 1 && pOwon[3] == 1 && pOwon[6] == 1) {
            return 1;
        }
        if (pOwon[1] == 1 && pOwon[4] == 1 && pOwon[7] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[5] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[4] == 1 && pOwon[6] == 1) {
            return 1;
        }
        if (pOwon[0] == 1 && pOwon[4] == 1 && pOwon[8] == 1) {
            return 1;
        }
        return 0;
    }

    public Bai25_TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        b1.setBackground(new java.awt.Color(255, 204, 204));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(204, 255, 204));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(255, 153, 153));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(0, 204, 204));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(51, 0, 255));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(102, 255, 204));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(204, 204, 0));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(204, 255, 255));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(255, 51, 255));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(204, 255, 204));
        reset.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 102, 255));
        reset.setText("Play Again!");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if (buttonused[0] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b0.setText("x");
                buttonused[0] = 1;

                pXwon[0] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b0.setText("o");
                buttonused[0] = 1;
                pOwon[0] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (buttonused[1] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b1.setText("x");
                buttonused[1] = 1;

                pXwon[1] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b1.setText("o");
                buttonused[1] = 1;
                pOwon[1] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (buttonused[2] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b2.setText("x");
                buttonused[2] = 1;

                pXwon[2] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b2.setText("o");
                buttonused[2] = 1;
                pOwon[2] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (buttonused[3] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b3.setText("x");
                buttonused[3] = 1;

                pXwon[3] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b3.setText("o");
                buttonused[3] = 1;
                pOwon[3] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (buttonused[4] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b4.setText("x");
                buttonused[4] = 1;

                pXwon[4] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b4.setText("o");
                buttonused[4] = 1;
                pOwon[4] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (buttonused[5] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b5.setText("x");
                buttonused[5] = 1;

                pXwon[5] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b5.setText("o");
                buttonused[5] = 1;
                pOwon[5] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (buttonused[6] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b6.setText("x");
                buttonused[6] = 1;

                pXwon[6] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b6.setText("o");
                buttonused[6] = 1;
                pOwon[6] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (buttonused[7] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b7.setText("x");
                buttonused[7] = 1;

                pXwon[7] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b7.setText("o");
                buttonused[7] = 1;
                pOwon[7] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (buttonused[8] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b8.setText("x");
                buttonused[8] = 1;

                pXwon[8] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            } else {
                turn++;
                b8.setText("o");
                buttonused[8] = 1;
                pOwon[8] = 1;
                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS ALREADY USED!");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        
        turn = 2;
        for (int i = 0;i < 9;i++){
           buttonused[i] = 0; 
        }
        for (int i = 0;i < 9;i++){
           pXwon[i] = 0; 
        }
        for (int i = 0;i < 9;i++){
           pOwon[i] = 0; 
        }
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai25_TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai25_TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai25_TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai25_TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai25_TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
